import type { Metadata } from "next";
import "./globals.css";
import "magic-pill/dist/magicpill.css";
import { MagicPillProvider } from "./contexts/magicPill";
import { MagicPillInitializer } from "./contexts/magicPillInitializer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MagicPillProvider>
          {children}
          <MagicPillInitializer />
        </MagicPillProvider>
      </body>
    </html>
  );
}
